name: Statuer
version: '${project.version}'
main: me.xap3y.statuer.Statuer

commands:
  statuer:
    description: Reloads the plugin configuration
    usage: /statuer
  Portunbind:
    description: Unbinds the ws PORT
    usage: /Portunbind
